cfg:
  uri: "ip:192.168.2.1"
  setup:
    devices:
      - ad9361-phy:
          attrs:
            - calib_mode: "manual"
            - ensm_mode: "fdd"
          debug-attrs:
            - loopback: 1
      - cf-ad9361-dds-core-lpc:
          channels:
            output:
              - voltage1:
                  attrs:
                    - sampling_frequency: 30719999
      - cf-ad9361-lpc:
          channels:
            input:
              - voltage0:
                  attrs:
                    - sampling_frequency: 30719999
          attrs:
            - sync_start_enable: "arm"
          buffer-attrs:
            - length_align_bytes: 8
